# Generated by Django 3.2.16 on 2024-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное название БД', max_length=255, verbose_name='Название')),
                ('host', models.CharField(help_text='IP-адрес или dns-имя сервера', max_length=255, verbose_name='Сервер')),
                ('port', models.IntegerField(verbose_name='Порт сервера')),
                ('user', models.CharField(help_text='Пользователь для подключения к БД', max_length=255, verbose_name='Пользователь')),
                ('password', models.CharField(help_text='Пароль для подключения к БД', max_length=255, verbose_name='Пароль')),
                ('database', models.CharField(max_length=255, verbose_name='Название БД')),
                ('active', models.BooleanField(help_text='Подключение происходит только к активным БД', verbose_name='Активна')),
            ],
        ),
    ]
