# Generated by Django 3.2.16 on 2024-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20240801_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное название сервиса', max_length=255, verbose_name='Название')),
                ('host', models.CharField(help_text='IP-адрес или dns-имя сервера', max_length=255, verbose_name='Сервер')),
                ('port', models.IntegerField(verbose_name='Порт сервера')),
                ('user', models.CharField(help_text='Пользователь для подключения к сервису', max_length=255, verbose_name='Пользователь')),
                ('password', models.CharField(help_text='Пароль для подключения к сервису', max_length=255, verbose_name='Пароль')),
                ('active', models.BooleanField(help_text='Подключение происходит только к активному сервису', verbose_name='Активен')),
                ('base_dn', models.CharField(help_text='В каком OU искать пользователей', max_length=300, verbose_name='Базовое уникальное имя')),
                ('seatch_filter', models.CharField(help_text='Позволяет искать объекты определенного типа', max_length=300, verbose_name='Фильтр')),
            ],
            options={
                'verbose_name': 'ActiveDirectory',
                'verbose_name_plural': 'ActiveDirectory',
                'ordering': ('id',),
            },
        ),
    ]
