# Generated by Django 3.2.16 on 2024-08-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_activedirectory_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mikrotik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное название сервиса', max_length=255, verbose_name='Название')),
                ('host', models.CharField(help_text='IP-адрес или dns-имя сервера', max_length=255, verbose_name='Сервер')),
                ('user', models.CharField(help_text='Пользователь для подключения к сервису', max_length=255, verbose_name='Пользователь')),
                ('password', models.CharField(help_text='Пароль для подключения к сервису', max_length=255, verbose_name='Пароль')),
                ('active', models.BooleanField(help_text='Подключение происходит только к активному сервису', verbose_name='Активен')),
                ('port', models.IntegerField(help_text='8728 - без ssl, 8729 - ssl', verbose_name='Порт сервера')),
                ('use_ssl', models.BooleanField(verbose_name='Использовать SSL')),
                ('ssl_verify', models.BooleanField(verbose_name='Проверять сертификат')),
                ('ssl_verify_hostname', models.BooleanField(help_text='Проверять dns-имя сервера с CN в сертификате', verbose_name='Проверять dns-имя сервера')),
            ],
            options={
                'verbose_name': 'Mikrotik',
                'verbose_name_plural': 'Mikrotik',
                'ordering': ('id',),
            },
        ),
    ]
