# Generated by Django 3.2.16 on 2024-08-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_mikrotik'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotik',
            name='need_disable',
            field=models.BooleanField(default=True, verbose_name='Блокировать учетные записи'),
            preserve_default=False,
        ),
    ]
