# Generated by Django 3.2.16 on 2024-08-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_mikrotik_need_disable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное название сервиса', max_length=255, verbose_name='Название')),
                ('user', models.CharField(help_text='Пользователь для подключения к сервису', max_length=255, verbose_name='Пользователь')),
                ('password', models.CharField(help_text='Пароль для подключения к сервису', max_length=255, verbose_name='Пароль')),
                ('active', models.BooleanField(help_text='Подключение происходит только к активному сервису', verbose_name='Активен')),
                ('host', models.CharField(help_text='IP-адрес или dns-имя сервера, пример: "http://inventory.yourdomen.org:5985/wsman" или "https://inventory.yourdomen.org:5986/wsman"', max_length=255, verbose_name='Сервер')),
                ('read_users_ps_script', models.TextField(help_text='Должен вернуть json строку', verbose_name='Скрипт чтения пользователей')),
                ('cert_validation', models.BooleanField(verbose_name='Проверять сертификат')),
                ('need_disable', models.BooleanField(verbose_name='Блокировать учетные записи')),
            ],
            options={
                'verbose_name': 'Radius',
                'verbose_name_plural': 'Radius',
                'ordering': ('id',),
            },
        ),
    ]
