# Generated by Django 3.2.16 on 2025-03-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_radiusserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное название сервиса', max_length=255, verbose_name='Название')),
                ('user', models.CharField(help_text='Пользователь для подключения к сервису', max_length=255, verbose_name='Пользователь')),
                ('password', models.CharField(help_text='Пароль для подключения к сервису', max_length=255, verbose_name='Пароль')),
                ('active', models.BooleanField(help_text='Подключение происходит только к активному сервису', verbose_name='Активен')),
                ('host', models.CharField(help_text='IP-адрес или dns-имя сервера, пример: "http://rocket.yourdomen.org" или "https://rocket.yourdomen.org"', max_length=255, verbose_name='Сервер')),
                ('need_disable', models.BooleanField(verbose_name='Блокировать учетные записи')),
            ],
            options={
                'verbose_name': 'RocketChat',
                'verbose_name_plural': 'RocketChat',
                'ordering': ('id',),
            },
        ),
    ]
