# Generated by Django 4.2.10 on 2026-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rocketchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PfSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольное название сервера', max_length=255, verbose_name='Название')),
                ('host', models.CharField(help_text='IP-адрес или dns-имя сервера', max_length=255, verbose_name='Сервер')),
                ('port', models.IntegerField(default=443, verbose_name='Порт')),
                ('api_token', models.CharField(max_length=255, verbose_name='API токен')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Использовать SSL')),
                ('active', models.BooleanField(default=True, help_text='Подключение происходит только к активному сервису', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'pfSense',
                'verbose_name_plural': 'pfSense',
                'ordering': ('id',),
            },
        ),
    ]
