# Generated by Django 4.2.10 on 2026-06-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_pfsense'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfsense',
            name='need_disable',
            field=models.BooleanField(default=False, verbose_name='Блокировать учетные записи'),
        ),
    ]
