# Generated by Django 3.2.16 on 2024-07-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radius',
            options={'ordering': ('login',)},
        ),
        migrations.AlterModelOptions(
            name='vpn',
            options={'ordering': ('login',)},
        ),
    ]
