# Generated by Django 3.2.16 on 2024-07-28 17:21

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_mysqldatabase_options'),
        ('users', '0002_auto_20240726_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigrotermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='inactive', max_length=15, verbose_name='Статус')),
                ('gigro_id', models.IntegerField(help_text='ID в БД Гигротермон', verbose_name='Гигро id')),
                ('ad_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.adusers', verbose_name='Пользователь AD')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mysqldatabase', verbose_name='БД Гигротермон')),
            ],
            options={
                'verbose_name': 'Пользователь Гигротермон',
                'verbose_name_plural': 'Пользователи Гигротермон',
                'ordering': ('login',),
            },
            bases=(users.models.BaseUserMixin, models.Model),
        ),
    ]
