# Generated by Django 3.2.16 on 2024-07-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gigrotermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigrotermon',
            name='ad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigro', to='users.adusers', verbose_name='Пользователь AD'),
        ),
        migrations.AddConstraint(
            model_name='gigrotermon',
            constraint=models.UniqueConstraint(fields=('login', 'db'), name='unique_login_db'),
        ),
    ]
