# Generated by Django 3.2.16 on 2024-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240729_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='adusers',
            name='successfully_updated',
            field=models.BooleanField(default=True, help_text='Если информация об учетной записи не поступила при последнем обновлении, галочка снимается, запись можно удалить.', verbose_name='Успешна обновлена'),
        ),
        migrations.AddField(
            model_name='gigrotermon',
            name='successfully_updated',
            field=models.BooleanField(default=True, help_text='Если информация об учетной записи не поступила при последнем обновлении, галочка снимается, запись можно удалить.', verbose_name='Успешна обновлена'),
        ),
        migrations.AddField(
            model_name='radius',
            name='successfully_updated',
            field=models.BooleanField(default=True, help_text='Если информация об учетной записи не поступила при последнем обновлении, галочка снимается, запись можно удалить.', verbose_name='Успешна обновлена'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='successfully_updated',
            field=models.BooleanField(default=True, help_text='Если информация об учетной записи не поступила при последнем обновлении, галочка снимается, запись можно удалить.', verbose_name='Успешна обновлена'),
        ),
        migrations.AlterField(
            model_name='adusers',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='adusers',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='inactive', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='radius',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='radius',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='inactive', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='inactive', max_length=15, verbose_name='Статус'),
        ),
    ]
