# Generated by Django 4.2.10 on 2026-06-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240806_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PfSenseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='inactive', max_length=15, verbose_name='Статус')),
                ('successfully_updated', models.BooleanField(default=True, help_text='Если информация об учетной записи не поступила при последнем обновлении, галочка снимается, запись можно удалить.', verbose_name='Успешно обновлена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('disabled', models.BooleanField(default=False, verbose_name='Отключен в pfSense')),
            ],
            options={
                'verbose_name': 'Пользователь pfSense',
                'verbose_name_plural': 'Пользователи pfSense',
                'ordering': ('login',),
            },
        ),
        migrations.AddField(
            model_name='adusers',
            name='pfsense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_user', to='users.pfsenseuser', verbose_name='Учетная запись pfSense'),
        ),
    ]
