# Generated by Django 4.2.10 on 2026-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pfsenseuser_adusers_pfsense'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfsenseuser',
            name='pfsense_id',
            field=models.CharField(blank=True, help_text='ID пользователя в pfSense (используется для блокировки)', max_length=50, null=True, verbose_name='ID pfSense'),
        ),
    ]
