# Generated by Django 4.2.10 on 2026-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pfsenseuser_pfsense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfsenseuser',
            name='pfsense_id',
            field=models.IntegerField(blank=True, help_text='ID пользователя в pfSense (используется для блокировки)', null=True, verbose_name='ID pfSense'),
        ),
    ]
