# Generated by Django 3.2.16 on 2023-08-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=100, verbose_name='Имя ПК')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('win_ver', models.CharField(max_length=100, verbose_name='Версия ОС')),
                ('os_arch', models.CharField(max_length=20, verbose_name='Архитектура')),
                ('cpu', models.CharField(max_length=50, verbose_name='Процессор')),
                ('motherboard', models.CharField(max_length=100, verbose_name='Материнская плата')),
            ],
            options={
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Департамент')),
            ],
        ),
        migrations.CreateModel(
            name='WebCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('install_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('uninstall_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата снятия')),
                ('capacity', models.CharField(max_length=20, verbose_name='Объем, Гб.')),
                ('serial_number', models.CharField(blank=True, default='Отсутствует', max_length=100, null=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('lost', 'Потерян'), ('installed', 'Установлен'), ('uninstalled', 'Снят')], default='installed', max_length=15, verbose_name='Статус модуля памяти')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rams', to='comps.comp')),
            ],
            options={
                'ordering': ['uninstall_date'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('install_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('uninstall_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата снятия')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('serial_number', models.CharField(blank=True, default='Отсутствует', max_length=100, null=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('lost', 'Потерян'), ('installed', 'Установлен'), ('uninstalled', 'Снят')], default='installed', max_length=15, verbose_name='Статус')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='comps.comp')),
            ],
            options={
                'ordering': ['uninstall_date'],
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('install_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('uninstall_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата снятия')),
                ('capacity', models.CharField(max_length=20, verbose_name='Объем, Гб.')),
                ('serial_number', models.CharField(blank=True, default='Отсутствует', max_length=100, null=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('lost', 'Потерян'), ('installed', 'Установлен'), ('uninstalled', 'Снят')], default='installed', max_length=15, verbose_name='Статус диска')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='comps.comp')),
            ],
            options={
                'ordering': ['uninstall_date'],
            },
        ),
        migrations.AddField(
            model_name='comp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='comps.department'),
        ),
        migrations.AddField(
            model_name='comp',
            name='web_camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_camera', to='comps.webcamera'),
        ),
    ]
