# Generated by Django 3.2.16 on 2023-09-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя хоста')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя виртуальной машины')),
            ],
        ),
        migrations.AlterField(
            model_name='comp',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='comps.department'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='web_camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='comps.webcamera'),
        ),
        migrations.CreateModel(
            name='HostVirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_vm', to='comps.host')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.virtualmachine')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='vms',
            field=models.ManyToManyField(through='comps.HostVirtualMachine', to='comps.VirtualMachine', verbose_name='Виртуальные машины'),
        ),
    ]
