# Generated by Django 3.2.16 on 2023-09-30 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_auto_20230929_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='uptime',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
        ),
    ]
