# Generated by Django 3.2.16 on 2023-10-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20230930_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMAdapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50, verbose_name='Мак-адрес')),
                ('vlan', models.IntegerField(verbose_name='VlanID')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter', to='comps.virtualmachine')),
            ],
        ),
    ]
