# Generated by Django 3.2.16 on 2023-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0004_vmadapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='vm_id',
            field=models.CharField(default='Не определен', max_length=100, verbose_name='ID виртуальной машины'),
        ),
    ]
