# Generated by Django 3.2.16 on 2023-10-09 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0006_alter_hostvirtualmachine_vm'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='Дата последнего подключения'),
        ),
    ]
