# Generated by Django 3.2.16 on 2024-07-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_comp_online_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp',
            options={'ordering': ('-add_date',), 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'ordering': ('uninstall_date',), 'verbose_name': 'Диск', 'verbose_name_plural': 'Диски'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('name',), 'verbose_name': 'Хост', 'verbose_name_plural': 'Хосты'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ('uninstall_date',), 'verbose_name': 'Монитор', 'verbose_name_plural': 'Мониторы'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ('uninstall_date',), 'verbose_name': 'RAM', 'verbose_name_plural': 'RAMs'},
        ),
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ('name',), 'verbose_name': 'Виртуальная машина', 'verbose_name_plural': 'Виртуальные машины'},
        ),
        migrations.AlterModelOptions(
            name='webcamera',
            options={'ordering': ('model',), 'verbose_name': 'Веб-камера', 'verbose_name_plural': 'Веб-камеры'},
        ),
        migrations.AlterField(
            model_name='comp',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp', to='comps.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='web_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp', to='comps.webcamera', verbose_name='Веб-камера'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='comps.comp', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='hostvirtualmachine',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_vm', to='comps.host', verbose_name='Хост'),
        ),
        migrations.AlterField(
            model_name='hostvirtualmachine',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_vm', to='comps.virtualmachine', verbose_name='Виртуальная машина'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='comps.comp', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='vmadapter',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter', to='comps.virtualmachine', verbose_name='Виртуальная машина'),
        ),
    ]
