# Generated by Django 3.2.16 on 2024-07-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_comp_online_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp', to='comps.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='web_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp', to='comps.webcamera', verbose_name='Веб-камера'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='comps.comp', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='hostvirtualmachine',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_vm', to='comps.host', verbose_name='Хост'),
        ),
        migrations.AlterField(
            model_name='hostvirtualmachine',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_vm', to='comps.virtualmachine', verbose_name='Виртуальная машина'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='comps.comp', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='vmadapter',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter', to='comps.virtualmachine', verbose_name='Виртуальная машина'),
        ),
    ]
