# Generated by Django 3.2.16 on 2024-07-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0008_auto_20240725_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp',
            options={'ordering': ('-add_date',), 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'ordering': ('uninstall_date',), 'verbose_name': 'Диск', 'verbose_name_plural': 'Диски'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('name',), 'verbose_name': 'Хост', 'verbose_name_plural': 'Хосты'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ('uninstall_date',), 'verbose_name': 'Монитор', 'verbose_name_plural': 'Мониторы'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ('uninstall_date',), 'verbose_name': 'RAM', 'verbose_name_plural': 'RAMs'},
        ),
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ('name',), 'verbose_name': 'Виртуальная машина', 'verbose_name_plural': 'Виртуальные машины'},
        ),
        migrations.AlterModelOptions(
            name='webcamera',
            options={'ordering': ('model',), 'verbose_name': 'Веб-камера', 'verbose_name_plural': 'Веб-камеры'},
        ),
    ]
